channels:
- ibmdecisionoptimization
- pyscf
- nvidia
- pytorch
- conda-forge
- defaults
dependencies:
- ca-certificates
- certifi
- cmake
- conan
- cudatoolkit
- cvxopt
- cython
- dill
- docplex
- fastdtw
- h5py
- ipywidgets
- jsonschema
- jupyterlab
- matplotlib
- mkl
- networkx
- numpy
- openmp
- openssl
- pandas
- pillow
- pip
- ply
- pre-commit
- psutil
- pybind11
- pygments
- pylatexenc
- pyscf
- python-constraint
- python-fastjsonschema
- python=3.7
- quandl
- requests
- requests_ntlm
- scikit-build
- scikit-learn
- scipy
- seaborn
- setuptools
- sympy
- tbb
- thrust
- urllib3
- websockets
- widgetsnbextension
- pip:
  - dlx
  - nest-asyncio
  - qiskit[visualization]
  - yfinance
name: qiskit-playground
