name: qiskit-playground
channels:
  - ibmdecisionoptimization
  - pyscf
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - cmake
  - conan
  - cudatoolkit
  - scikit-build
  - setuptools
  - numpy
  - mkl
  - thrust
  - tbb
  - cython
  - openmp
  - pybind11
  - scipy
  - cvxopt
  - fastdtw
  - h5py
  - pandas
  - psutil
  - quandl
  - networkx
  - scikit-learn
  - requests
  - urllib3
  - websockets
  - dill
  - jsonschema
  - ply
  - sympy
  - matplotlib
  - ipywidgets
  - jupyterlab
  - widgetsnbextension
  - pillow
  - pygments
  - pylatexenc
  - seaborn
  - ca-certificates
  - openssl
  - pre-commit
  - certifi
  - pyscf
  - docplex
  - requests_ntlm
  - python-fastjsonschema
  - python-constraint
  - pip:
      - yfinance
      - dlx
      - nest-asyncio
      - "qiskit[visualization]"

